function dx0dthSym = dICdthDewasme(in1,in2)
%DICDTHDEWASME
%    DX0DTHSYM = DICDTHDEWASME(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-Jul-2021 19:56:35

dx0dthSym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
