%% codigo para leer datos obtenidos de hippo, pueden agregar o quitar valores segun lo deseen (solo es una base) 

load('it.mat'); % loads result matrix (it.mat generated by HIPPO)

param=5;  % Number of model parameters
nresult=3; % Number of models evaluated by HIPPO

datos=it.codes(:,2);
codigos=it.codes(:,1);

for i=1:1:nresult

Akaike(i)= datos{i,1}.AICc;
BIC(i)= datos{i,1}.BIC;
Fobj(i)= datos{i,1}.J_SSm;
FFF(i)=i;

%% Significance vector: How many k are not significant (CC>=2)? 
% For each model:
CCc(i)=length(find(datos{i,1}.CC>=2));

%% Sensibility vector: How many k are not sensible?
% For each model:
MS(i)= length(find(datos{i,1}.Ms==0));

%% Identificability analysis: 
I15(i)=length(find(datos{i,1}.Mc>0.95));
I125(i)=length(find(datos{i,1}.Mc<-0.95));
I95(i)=I15(i)+I125(i);

if I95(i)==param-sum(codigos{i,1})
    I955(i)=0; % No identificability problems
    
else
    I955(i)=1; % Identificability problems

    end 

end
%% Results:
%          1    2     3     4      5    6    7   
results= [FFF' Fobj' CCc' Akaike' BIC' MS' I955'];

% Saves 'results' matrix in an Excel file
b=array2table(results,'VariableNames',{'FFF', 'Fobj','CCc','Akaike','BIC','MS','I955'});
filename = 'HIPPO_Results.xlsx';
writetable(b,filename);

