function x0Sym = x0Xu(in1)
%X0XU
%    X0SYM = X0XU(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Jul-2021 20:22:42

x0Sym = [1.01e+2./2.5e+1;1.0./1.0e+3;7.9e+1./2.0e+1;7.0./1.0e+3;3.0./1.0e+1];
