function x0Sym = x0Anane(in1)
%X0ANANE
%    X0SYM = X0ANANE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Jul-2021 23:35:46

x0Sym = [1.01e+2./2.5e+1;1.0./1.0e+3;7.9e+1./2.0e+1;7.0./1.0e+3;3.0./1.0e+1];
