function x0Sym = x0Anane(in1)
%X0ANANE
%    X0SYM = X0ANANE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Jul-2021 16:52:58

x0Sym = [3.3e+1./8.0;1.0./1.0e+3;5.13e+2./1.25e+2;7.0./1.0e+3;3.0./1.0e+1];
