function dx0dthSym = dICdthDewasme(in1,in2)
%DICDTHDEWASME
%    DX0DTHSYM = DICDTHDEWASME(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Jul-2021 18:50:53

dx0dthSym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,11]);
