function dx0dthSym = dICdthAnane(in1,in2)
%DICDTHANANE
%    DX0DTHSYM = DICDTHANANE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Jul-2021 16:48:25

dx0dthSym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,13]);
